// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sabemi.PaymentWebhook.Infrastructure.Persistence;

#nullable disable

namespace Sabemi.PaymentWebhook.Infrastructure.Migrations
{
    [DbContext(typeof(PaymentWebhookDbContext))]
    partial class PaymentWebhookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sabemi.PaymentWebhook.Infrastructure.Persistence.Entities.PagamentoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdContrato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdTransacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdTransacao")
                        .IsUnique();

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("Sabemi.PaymentWebhook.Infrastructure.Persistence.Entities.PagamentoEventoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Erro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdTransacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Processado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RecebidoEm")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PagamentoEventos");
                });

            modelBuilder.Entity("Sabemi.PaymentWebhook.Infrastructure.Persistence.Entities.StatusContratoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdContrato")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdContrato")
                        .IsUnique();

                    b.ToTable("StatusContratos");
                });
#pragma warning restore 612, 618
        }
    }
}
